version: "3"

volumes:
  pg_data: {}

services:
  web:
    platform: linux/amd64
    build:
      context: .
    volumes:
      - ./apiserver:/app
    ports:
      - "8111:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=apiserver.settings.local
    restart: always
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0:8000
  db:
    image: postgres:12
    shm_size: 1g
    ports:
      - 34512:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=webdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=34512